# Generated by Django 4.0 on 2022-11-28 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gameadmin', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingroom',
            name='admin',
            field=models.CharField(default='a', max_length=150),
        ),
        migrations.AddField(
            model_name='startingroom',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
