# Generated by Django 4.0 on 2023-05-15 20:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enumeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='enumeration_played',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number_played', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('code', models.IntegerField(max_length=100, unique=True)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='priv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('code', models.IntegerField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='room_created',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('room_created', models.CharField(blank=True, max_length=10, null=True)),
                ('players', models.CharField(blank=True, max_length=1000, null=True)),
                ('table', models.TextField(default='', max_length=10000000000000000000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('code', models.IntegerField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('num', models.CharField(default='', max_length=200)),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='total_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.CharField(max_length=1000000)),
                ('user', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='played_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('code', models.IntegerField(max_length=1000)),
                ('name', models.CharField(default='', max_length=200)),
                ('ids', models.BigIntegerField(default=0)),
            ],
            options={
                'unique_together': {('code', 'user')},
            },
        ),
    ]
