# Generated by Django 4.0 on 2023-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='data',
            field=models.CharField(max_length=10000000),
        ),
    ]
