# Generated by Django 4.0 on 2023-04-02 12:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_mymodel_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None),
        ),
    ]
