# Generated by Django 4.0 on 2023-05-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumeration_played',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
