# Generated by Django 4.0 on 2023-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_enumeration_played_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enumeration_played',
            name='code',
        ),
        migrations.AddField(
            model_name='total_score',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
