# Generated by Django 4.0 on 2023-04-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
