# Generated by Django 4.0 on 2023-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_enumeration_played_code_total_score_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_score',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
