# Generated by Django 4.0 on 2023-04-04 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_title_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
