# Generated by Django 4.0 on 2023-04-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_title_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_created',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('room_created', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('players', models.CharField(blank=True, max_length=1000, null=True)),
                ('table', models.TextField(default='', max_length=10000000000000000000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
