# Generated by Django 4.0 on 2023-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_enumeration_played_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumeration_played',
            name='code',
            field=models.CharField(default='f3', max_length=100),
        ),
    ]
