# Generated by Django 4.0 on 2023-04-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_room_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_created',
            name='room_created',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
