# Generated by Django 4.0 on 2023-05-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_room_created_room_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='edit',
            field=models.TextField(default='', max_length=10000000000000000000),
        ),
    ]
