# Generated by Django 4.0 on 2024-06-27 01:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000000000), blank=True, size=None),
        ),
    ]
