# Generated by Django 4.0 on 2023-05-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_title_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='edit',
        ),
    ]
