# Generated by Django 4.0 on 2023-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_title_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='num',
            field=models.CharField(default='', max_length=200),
        ),
    ]
