# Generated by Django 4.0 on 2023-05-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_mymodel_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
