# Generated by Django 4.0 on 2023-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_title_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='enumeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
