# Generated by Django 4.0 on 2023-05-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_enumeration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='code',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
