# Generated by Django 4.0 on 2023-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_alter_mymodel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='priv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=True)),
                ('code', models.IntegerField(max_length=100, unique=True)),
            ],
        ),
    ]
