# Generated by Django 4.0 on 2023-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_played_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='played_quiz',
            name='code',
            field=models.IntegerField(max_length=100),
        ),
    ]
