# Generated by Django 4.0 on 2023-05-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_played_quiz_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='played_quiz',
            unique_together={('code', 'user')},
        ),
    ]
