# Generated by Django 4.0 on 2022-10-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_created',
            name='players',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='room_created',
            name='table',
            field=models.TextField(default='', max_length=10000000000000000000),
        ),
        migrations.AlterField(
            model_name='room_created',
            name='room_created',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room_created',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
