# Generated by Django 4.0 on 2022-12-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_room_created_players_room_created_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='played',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('room_played', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
    ]
