# Generated by Django 4.0 on 2022-08-25 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adnan_test11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(max_length=150)),
                ('gnoun', models.CharField(max_length=150)),
                ('animalNoun', models.CharField(max_length=150)),
                ('plants', models.CharField(max_length=150)),
                ('countries', models.CharField(max_length=150)),
                ('inanimate', models.CharField(max_length=150)),
                ('sum', models.CharField(max_length=150)),
                ('user', models.CharField(max_length=150)),
                ('letter', models.CharField(default='أ', max_length=150)),
                ('room', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='summeryOfLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_letter_as', models.CharField(max_length=2000)),
                ('room', models.CharField(max_length=150)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 8, 25, 19, 54, 19, 170606))),
            ],
        ),
    ]
