# Generated by Django 4.0 on 2022-08-27 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_alter_summeryofletter_all_letter_as_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 0, 25, 2, 475295)),
        ),
    ]
