# Generated by Django 4.0 on 2022-08-30 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='startingroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=150)),
                ('started', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 0, 57, 19, 797624)),
        ),
    ]
