# Generated by Django 4.0 on 2022-09-16 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0013_alter_array_status_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='array',
            name='status',
            field=models.CharField(blank=True, default='first', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 18, 42, 57, 77129)),
        ),
    ]
