# Generated by Django 4.0 on 2022-12-05 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0026_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_created',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('room_created', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('players', models.CharField(blank=True, max_length=1000, null=True)),
                ('table', models.TextField(default='', max_length=10000000000000000000)),
            ],
        ),
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 16, 55, 57, 526108, tzinfo=utc)),
        ),
    ]
