# Generated by Django 4.0 on 2022-12-05 17:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0027_room_created_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_created',
            name='room_created',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 17, 1, 17, 397647, tzinfo=utc)),
        ),
    ]
