# Generated by Django 4.0 on 2022-12-13 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0028_alter_room_created_room_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 54, 24, 553102, tzinfo=utc)),
        ),
    ]
