# Generated by Django 4.0 on 2023-05-06 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0046_lang_user_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='user',
            field=models.CharField(default='arabic', max_length=150),
        ),
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 15, 2, 48, 290745, tzinfo=utc)),
        ),
    ]
