# Generated by Django 4.0 on 2023-05-06 22:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0047_alter_lang_user_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 22, 31, 48, 980370, tzinfo=utc)),
        ),
    ]
