# Generated by Django 4.0 on 2024-06-19 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0095_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 0, 1, 48, 111800, tzinfo=utc)),
        ),
    ]
