# Generated by Django 4.0 on 2024-06-20 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0099_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 20, 13, 47, 5, 902368, tzinfo=utc)),
        ),
    ]
