# Generated by Django 4.0 on 2024-06-27 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0100_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 1, 2, 36, 759690, tzinfo=utc)),
        ),
    ]
