# Generated by Django 4.0 on 2022-09-16 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0011_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='array',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1000)),
                ('room', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 17, 54, 4, 997948)),
        ),
    ]
