# Generated by Django 4.0 on 2022-09-16 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0012_array_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='array',
            name='status',
            field=models.CharField(default='first', max_length=1000),
        ),
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 18, 35, 7, 893922)),
        ),
    ]
