# Generated by Django 4.0 on 2022-09-22 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0015_players_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='players',
            field=models.CharField(blank=True, max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 20, 32, 28, 821606)),
        ),
    ]
