# Generated by Django 4.0 on 2022-09-27 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0016_alter_players_players_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnan_test11',
            name='letter',
            field=models.CharField(blank=True, default='أ', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 0, 36, 20, 303520)),
        ),
    ]
