# Generated by Django 4.0 on 2022-10-06 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0017_alter_adnan_test11_letter_alter_summeryofletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summeryofletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 22, 21, 19, 785211)),
        ),
    ]
